default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: semcomp
  password: 123
  host: localhost
  port: 5432

development:
  <<: *default
  database: buzzer2_development

test:
  <<: *default
  database: buzzer2_test

