development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pguser
  password: 123
  database: buzzer_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pguser
  password: 123
  database: buzzer_test
